<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251211161455 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text_value TEXT DEFAULT NULL, selected_options JSON DEFAULT NULL, rating_value INT DEFAULT NULL, response_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50D0C606FBF32840 ON answers (response_id)');
        $this->addSql('CREATE INDEX IDX_50D0C6061E27F6BF ON answers (question_id)');
        $this->addSql('CREATE TABLE questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, type VARCHAR(50) NOT NULL, options JSON DEFAULT NULL, is_required BOOLEAN NOT NULL, position INT NOT NULL, survey_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8ADC54D5B3FE509D ON questions (survey_id)');
        $this->addSql('CREATE TABLE responses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, survey_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_315F9F94B3FE509D ON responses (survey_id)');
        $this->addSql('CREATE TABLE surveys (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C606FBF32840 FOREIGN KEY (response_id) REFERENCES responses (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C6061E27F6BF FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE questions ADD CONSTRAINT FK_8ADC54D5B3FE509D FOREIGN KEY (survey_id) REFERENCES surveys (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE responses ADD CONSTRAINT FK_315F9F94B3FE509D FOREIGN KEY (survey_id) REFERENCES surveys (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C606FBF32840');
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C6061E27F6BF');
        $this->addSql('ALTER TABLE questions DROP CONSTRAINT FK_8ADC54D5B3FE509D');
        $this->addSql('ALTER TABLE responses DROP CONSTRAINT FK_315F9F94B3FE509D');
        $this->addSql('DROP TABLE answers');
        $this->addSql('DROP TABLE questions');
        $this->addSql('DROP TABLE responses');
        $this->addSql('DROP TABLE surveys');
    }
}
